repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.4
  hooks:
    # Run the linter.
  - id: ruff
    args: [ --fix ]
  # Run the formatter.
  - id: ruff-format

-   repo: https://github.com/python-poetry/poetry
    rev: '2.0.1'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-install

-   repo: https://github.com/python-poetry/poetry-plugin-export
    rev: '1.9.0'
    hooks:
    -   id: poetry-export
